version: "3.1"
services:
  web:
    build:
      context: ./docker
      dockerfile: Dockerfile_dev
    image: lanorme_orchestrator_dev:latest
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/app
    user: "${UID}:${GID}"
    tty: true
    stdin_open: true
    command: sh -c "cd /app/philo; mix run --no-halt"
    environment:
      - DISPLAY=:0
