FROM elixir:1.12

RUN DEBIAN_FRONTEND=noninteractive apt update && apt install -y \
    build-essential \
    ca-certificates \
    curl \
    gnupg \
    lsb-release

RUN curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

RUN echo \
    "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian \
    buster stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

RUN DEBIAN_FRONTEND=noninteractive apt update && apt install -y \ 
    docker-ce \
    docker-ce-cli \
    containerd.io

# RUN locale-gen fr_FR.UTF-8  
ENV LANG C.UTF-8
ENV LANGUAGE fr_FR:fr
ENV LC_ALL C.UTF-8

ENV MIX_HOME=/workspace/mix \
    HEX_HOME=/workspace/hex \
    HOME=/workspace/home

EXPOSE 4000

CMD /bin/bash
