FROM elixir:1.12

# RUN locale-gen fr_FR.UTF-8  
ENV LANG C.UTF-8
ENV LANGUAGE fr_FR:fr
ENV LC_ALL C.UTF-8

ENV MIX_HOME=/workspace/mix \
    HEX_HOME=/workspace/hex \
    HOME=/workspace/home

CMD /bin/bash
